require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'SecStorage' do
  use_expo_modules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )

    installer.pods_project.targets.each do |target|
      next unless target.name == 'RNArgon2'

      target.build_configurations.each do |build_configuration|
        build_configuration.build_settings['SWIFT_INCLUDE_PATHS'] = [
          '$(inherited)',
          '"${PODS_CONFIGURATION_BUILD_DIR}/Argon2Swift"',
          '"${PODS_ROOT}/Argon2Swift/Sources/Modules"',
          '"${PODS_ROOT}/Argon2Swift/Sources/Argon2"',
          '"${PODS_ROOT}/Argon2Swift/Sources/Argon2/include"'
        ].join(' ')
      end
    end

    rn_argon2_swift = File.expand_path(
      '../node_modules/react-native-argon2/ios/RNArgon2.swift',
      __dir__
    )
    if File.exist?(rn_argon2_swift)
      contents = File.read(rn_argon2_swift)
      unless contents.include?("import React\n")
        File.write(
          rn_argon2_swift,
          contents.sub("import Foundation\n", "import Foundation\nimport React\n")
        )
      end
    end

    rn_argon2_umbrella_header = File.join(
      installer.sandbox.root.to_s,
      'Target Support Files',
      'RNArgon2',
      'RNArgon2-umbrella.h'
    )
    if File.exist?(rn_argon2_umbrella_header)
      contents = File.read(rn_argon2_umbrella_header)
      File.write(
        rn_argon2_umbrella_header,
        contents.gsub(%{#import "RNArgon2-Bridging-Header.h"\n}, '')
      )
    end
  end
end
